'use client';

import React from 'react';

/**
 * Site-wide disclaimer.
 *
 * The app presents dollar returns, Sharpe ratios and a one-word verdict, which
 * reads like investment guidance whether or not it is meant that way. The
 * README carrying a disclaimer is no use to someone who arrives at a results
 * page from a link, so it belongs where the numbers are.
 *
 * Rendered in the root layout, so every route inherits it.
 */
export default function Disclaimer() {
  return (
    <footer className="mt-16 border-t border-glass-border/60 bg-dark-secondary/40 backdrop-blur-glass">
      <div className="max-w-5xl mx-auto px-6 py-8 space-y-3">
        <p className="text-sm font-semibold text-white/80">
          Educational project, not financial advice
        </p>

        <p className="text-xs leading-relaxed text-white/50">
          Every result on this site is a <strong className="text-white/70">simulation</strong> run
          against historical price data. No trades are placed and no money is at risk.
          Backtested performance is not a prediction: past results do not indicate
          future returns, and a strategy that performed well historically can lose
          money in live markets.
        </p>

        <p className="text-xs leading-relaxed text-white/50">
          Strategy code is generated by a language model and may contain errors or
          misinterpret your intent. Simulations exclude slippage, market impact,
          liquidity limits, borrowing costs and taxes, all of which reduce real-world
          returns. Nothing here is a recommendation to buy or sell any security.
          Consult a qualified financial adviser before making investment decisions.
        </p>

        <p className="text-xs text-white/40 pt-2">
          A personal portfolio project demonstrating multi-agent orchestration on
          Amazon Bedrock AgentCore. Capacity is capped, so backtests may be
          temporarily unavailable.
        </p>
      </div>
    </footer>
  );
}
