"""
Backtest Execution Tool
Runs trading strategy backtests using the BacktestTool class
"""

import time
import pandas as pd
from strands import tool
import config
from tools.backtest import BacktestTool


# Initialize backtest tool
backtest_tool = BacktestTool()


@tool
def run_backtest(symbol: str, strategy_code: str, params: dict = None) -> dict:
    """
    Execute trading strategy backtest using historical market data.
    Reads market data from AgentCore Memory and saves results back to memory.

    Args:
        symbol: the strategy equity code, default AMZN
        strategy_code: Complete Backtrader strategy code from strategy_generator
        params: Optional backtest parameters (cash, commission, etc.)

    Returns:
        Comprehensive backtest results with performance metrics and statistics
    """
    agent_name = "⚡ BACKTEST AGENT"
    print("\n" + "="*50)
    print(agent_name)
    print("="*50)

    # Validate strategy code
    if not strategy_code or len(strategy_code.strip()) < 100:
        print("❌ ERROR: Invalid or empty strategy code")
        return {'error': 'Invalid or empty strategy code'}

    # Save strategy_code as fallback (in case generate_trading_strategy failed/skipped)
    if not config._generated_strategy_code:
        config._generated_strategy_code = strategy_code
        print(f"⚠️ [STRATEGY SOURCE] Strategy code was SELF-GENERATED by the LLM agent (not from Strategy Generator Runtime)")
        print(f"📝 Self-generated strategy code captured in run_backtest ({len(strategy_code)} chars)")
    else:
        print(f"✅ [STRATEGY SOURCE] Strategy code from Strategy Generator Runtime ({len(config._generated_strategy_code)} chars)")

    # Check if market data is available
    if config._stored_market_data is None or not config._stored_market_data:
        print("⚠️ No market data found in global storage")
        return {'error': 'No market data found in global storage'}

    # Extract the first symbol's data (assuming single symbol for now)
    symbol_key = symbol
    symbol_data = config._stored_market_data[symbol_key]

    # print(f"🔍 DEBUG - Available symbols: {list(config._stored_market_data.keys())}")
    print(f"🔍 DEBUG - Using symbol: {symbol_key}")

    # Get the transformed daily data
    daily_data = symbol_data.get('daily_data', [])

    if not daily_data:
        print("❌ NO MARKET DATA AVAILABLE - Cannot run backtest")
        return {'error': 'No market data available for backtesting'}

    df = pd.DataFrame(daily_data)

    # Convert date column to datetime and set as index
    df['date'] = pd.to_datetime(df['date'])
    df.set_index('date', inplace=True)

    # Ensure numeric columns are properly typed for Backtrader
    numeric_columns = ['open', 'high', 'low', 'close', 'volume', 'adj_close']
    for col in numeric_columns:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')

    print(f"📈 DataFrame created with columns: {list(df.columns)}")
    # print(f"📅 Date range: {df.index.min()} to {df.index.max()}")

    # 🔍 COMPREHENSIVE DEBUG INFO FOR BACKTRADER ERROR TROUBLESHOOTING
    print(f"\n🔬 DEBUG - DataFrame Analysis:")
    print(f"   Shape: {df.shape}")
    print(f"   Index type: {type(df.index)}")
    print(f"   Index name: {df.index.name}")
    print(f"   Columns: {list(df.columns)}")
    print(f"   Data types:")
    for col in df.columns:
        print(f"     {col}: {df[col].dtype}")

    # Print sample data for inspection
    print(f"\n📊 Sample data (first 3 rows):")
    try:
        print(df.head(3).to_string())
    except Exception as e:
        print(f"❌ Error displaying sample data: {e}")

    # Prepare backtest input
    backtest_input = {
        'strategy_code': strategy_code,
        'market_data': {symbol_key: df},  # Pass DataFrame for Backtrader
        'params': params or {'initial_cash': 100000, 'commission': 0.001}
    }

    print(f"📥 INPUT: strategy_code length: {len(strategy_code)}, symbol: {symbol_key}, rows: {len(daily_data)}")
    print(f"🧠 REASONING: Running strategy backtest with historical data...")

    # Execute backtest with enhanced error handling
    start_time = time.time()
    print(f"🚀 Starting backtest execution...")

    try:
        result = backtest_tool.process(backtest_input)

        # Check if result contains detailed error information
        if isinstance(result, dict) and 'error' in result:
            # print(f"❌ BACKTEST FAILED WITH DETAILED ERROR:")
            # print(f"   Error: {result['error']}")

            if 'error_location' in result:
                print(f"   Location: {result['error_location']}")

            if 'debug_info' in result:
                print(f"   Debug Info: {result['debug_info']}")

            if 'traceback' in result:
                print(f"   📋 FULL TRACEBACK:")
                print(result['traceback'])
        else:
            print(f"✅ Backtest execution completed")

    except Exception as backtest_error:
        print(f"❌ BACKTEST TOOL EXCEPTION:")
        print(f"   Error type: {type(backtest_error).__name__}")
        print(f"   Error message: {str(backtest_error)}")

        # Try to get more detailed error info
        import traceback
        print(f"   Full traceback:")
        traceback.print_exc()

        result = {'error': f'Backtest tool exception: {str(backtest_error)}'}
    processing_time = time.time() - start_time

    print(f"⏱️ Backtest completed in {processing_time:.2f} seconds")

    # Log trade details for debugging
    if 'error' not in result:
        trades = result.get('trades', [])
        trade_summary = result.get('trade_summary', {})
        print(f"📊 TRADES CAPTURED: {len(trades)} trades")
        for i, t in enumerate(trades):
            print(f"   Trade {i+1}: {t.get('direction')} {t.get('entry_date')} -> {t.get('exit_date')} | P&L: ${t.get('pnl', 0):.2f}")
        print(f"📊 TRADE SUMMARY: {trade_summary}")

        # Store result globally so invoke() can access it directly
        config._last_backtest_result = result
        print(f"💾 Stored backtest result with {len(trades)} trades in _last_backtest_result")

        # Also save to AgentCore Memory for historical queries
        config.save_backtest_results_to_memory_sync(result, strategy_code=strategy_code)
    else:
        print(f"📤 OUTPUT (error): {result}")

    print("="*50)
    return result
