"""
Strategy Generator Tool
Converts natural language trading strategies into executable Backtrader code
"""

import os
import json
import uuid
import time
from strands import tool
import config


@tool
def generate_trading_strategy(query: str) -> str:
    """
    Generate executable trading strategy code from natural language descriptions.

    Args:
        query: Natural language trading strategy in JSON format with sample below:
         {
            "name": "EMA Crossover Strategy",
            "stock_symbol": "AMZN",
            "backtest_window": "1Y",
            "max_positions": 1,
            "stop_loss": 5,
            "take_profit": 10,
            "buy_conditions":  "Price above 20-day moving average and RSI below 70",
            "sell_conditions": "Price below 20-day moving average or RSI above 80"
        }

    Returns:
        Complete Backtrader strategy Python code ready for backtesting
    """

    agent_name = "🧠 STRATEGY GENERATOR AGENT"
    print("\n" + "="*50)
    print(agent_name)
    print("="*50)

    input_data = query
    reasoning = "Converting user trading idea into executable strategy code..."

    print("="*50)
    print(f"📥 INPUT: {input_data}")
    print(f"🧠 REASONING: {reasoning}")

    print("⏳ Processing strategy generation (synchronous)...")

    # Record start time for monitoring
    start_time = time.time()

    try:
        # Call strategy agent and wait for completion
        result = config._agentcore_runtime_client.invoke_agent_runtime(
            agentRuntimeArn=os.getenv('STRATEGY_GENERATOR_RUNTIME_ARN'),
            runtimeSessionId=str(uuid.uuid4()),  # Unique session ID
            payload=json.dumps(input_data).encode('utf-8'),
            qualifier="DEFAULT"                  # Optional; version/endpoint control
        )

        # Calculate processing time
        processing_time = time.time() - start_time

        print(f"⏱️ Strategy generation completed in {processing_time:.2f} seconds")

        # Parse the AgentCore runtime response
        if 'response' in result:
            response_body = result['response'].read().decode('utf-8')
        elif 'body' in result:
            response_body = result['body'].read().decode('utf-8')
        else:
            response_body = str(result)

        response_data = json.loads(response_body)

        # Extract version if present
        # invoke_agent_runtime returns the agent's output as a JSON-encoded string
        # strategy_generator now returns {"code": "...", "version": "..."}
        if isinstance(response_data, str):
            strategy_code = response_data
        elif isinstance(response_data, dict):
            # Check if this is the new format with code and version
            if 'code' in response_data:
                strategy_code = response_data['code']
                config._strategy_generator_version = response_data.get('version', 'unknown')
                print(f"📌 Strategy Generator Version: {config._strategy_generator_version}")
            elif 'result' in response_data and isinstance(response_data['result'], dict) and 'content' in response_data['result']:
                content = response_data['result']['content']
                if isinstance(content, list) and len(content) > 0:
                    strategy_code = content[0].get('text', '')
                else:
                    strategy_code = str(content)
            else:
                strategy_code = response_body
        else:
            strategy_code = str(response_data)

        # Ensure we have a valid result before proceeding
        if not strategy_code or len(str(strategy_code).strip()) < 50:
            print("⚠️ Strategy generation returned insufficient content")
            return "Error: Strategy generation failed - insufficient content returned"

        print("✅ [STRATEGY SOURCE] Strategy code generated by Strategy Generator Runtime (tool call succeeded)")
        print("="*50)

        # Save strategy code for inclusion in final response
        config._generated_strategy_code = strategy_code

        # Add a small delay to ensure completion
        time.sleep(1)

        return strategy_code

    except Exception as e:
        processing_time = time.time() - start_time
        print(f"❌ Strategy generation failed after {processing_time:.2f} seconds: {e}")
        print("⚠️ [STRATEGY SOURCE] Strategy Generator Runtime FAILED. The LLM agent will self-generate the strategy code.")
        print("="*50)
        raise
